# Generated by Django 3.2.3 on 2021-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('modificacion', models.DateTimeField()),
                ('tipo_pago', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('idFiado', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('abono', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('modificacion', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('idMetodoPago', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_producto',
            fields=[
                ('idPedidoProducto', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoProducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('familia_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('precio_costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutEmpresa', models.CharField(max_length=10)),
                ('razon_social', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('idTipoProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta_detalle',
            fields=[
                ('idVentaDetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('monto_total', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('modificacion', models.DateTimeField()),
            ],
        ),
    ]
