# Generated by Django 3.2.3 on 2021-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0003_auto_20210530_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
