# Generated by Django 3.2.3 on 2021-05-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0004_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
