# Generated by Django 3.2.3 on 2021-06-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0005_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
