# Generated by Django 3.2.3 on 2021-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0006_remove_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.BigIntegerField(),
        ),
    ]
