# Generated by Django 3.2.3 on 2021-06-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0007_alter_producto_codigoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiado',
            name='cliente',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='yuyitosApp.cliente'),
        ),
    ]
