# Generated by Django 3.2.3 on 2021-06-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0008_fiado_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiado',
            old_name='cliente',
            new_name='clienteId',
        ),
    ]
