# Generated by Django 3.2.3 on 2021-06-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0009_rename_cliente_fiado_clienteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiado',
            old_name='clienteId',
            new_name='cliente',
        ),
    ]
