# Generated by Django 3.2.3 on 2021-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0010_rename_clienteid_fiado_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='folio',
            field=models.IntegerField(default=2),
        ),
    ]
