# Generated by Django 3.2.3 on 2021-06-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0011_boleta_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_detalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yuyitosApp.producto'),
        ),
        migrations.AlterField(
            model_name='venta_detalle',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
