# Generated by Django 3.2.3 on 2021-06-15 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0012_auto_20210604_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta_detalle',
            name='monto_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
