# Generated by Django 3.2.3 on 2021-06-16 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0014_auto_20210616_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta_detalle',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venta_detalle',
            name='monto',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
