# Generated by Django 3.2.3 on 2021-06-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0015_auto_20210616_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_detalle',
            name='cliente',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='yuyitosApp.cliente'),
        ),
    ]
