# Generated by Django 3.2.3 on 2021-06-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuyitosApp', '0016_venta_detalle_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_detalle',
            name='metodoPago',
        ),
    ]
